### ISSUE TITLE
Nested classes support?

### ISSUE THREAD

**Issue by sgrassie** [JonPSmith/EfSchemaCompare#11]
I've found that when a DbContext has mappings to a class in the same assembly, which is a nested class, then the comparer thinks the type is defined in another assembly.

Making the classes not nested is the obvious solution, but that would be... not easy.

**Comment by JonPSmith** [comment]
Hi @sgrassie,

I'm sorry to say that I don't support this EF6 library anymore. EF6 didn't provide very good access to the EF6 Model information which makes it very hard to debug / change. 

I do have an [EfCore.SchemaCompare](https://github.com/JonPSmith/EfCore.SchemaCompare) which is much better as EF Core has a `context.Model` which makes it much easier to code.

**Comment by sgrassie** [comment]
I appreciate that 😀 however with a particular project I'm in a legacy situation which is probably never going to change. I've forked the repo, so I will attempt to hack in the support I need 👍

**Comment by JonPSmith** [comment]
That's fine. I don't want to work on this library but its open-source code so go ahead. I suspect your changes will be feeding in your entity classes which should be OK, but if you need to change the deeper code, then be aware its not documented.
